cc_library(
  name = "bignum",
  srcs = [],
  hdrs = [
    "bignum.hpp"
  ],
  deps = [],
  visibility = [
    "//visibility:public",
  ]
)

cc_binary(
  name = "bignum_test",
  srcs = [
    "bignum_test.cc",
  ],
  deps = [
    ":bignum",
    "//baselib:baselib",
  ],
)