cc_binary(
  name = "dijkstra",
  srcs = [
    "dijkstra.cc",
  ],
  copts = [],
  deps = [],
)

cc_binary(
  name = "negative_ring",
  srcs = [
    "negative_ring.cc",
  ],
  copts = [],
  deps = [],
)


cc_binary(
  name = "hungarian",
  srcs = [
    "hungarian.cc",
  ],
  copts = ["-fpermissive"],
  deps = [],
)

cc_binary(
  name = "floyd",
  srcs = [
    "floyd.cc",
  ],
  copts = ["-fpermissive"],
  deps = [],
)