cc_binary(
  name = "kmp",
  srcs = [
    "kmp.cc",
  ],
  copts = [],
  deps = [],
)


cc_binary(
  name = "multi-hash_test",
  srcs = [
    "multi-hash_test.cc",
    "multi-hash.hpp",
  ]
)

cc_binary(
  name = "luoguP3370",
  srcs = ["luoguP3370.cc"]
)