cc_library(
  name = "sort",
  srcs = [],
  hdrs = ["sort.hpp"],
  deps = [],
  visibility = [
    "//visibility:public",
  ]
)

cc_binary(
  name = "sort_test",
  srcs = ["sort_test.cc"],
  copts = [],
  deps = [
    ":sort",
    "//baselib:baselib",
  ],
)